version: '3'
services:
  kserver:
    image: adriaquintero61/k19:kserver
    container_name: kserver.edt.org
    hostname: kserver.edt.org
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    networks:
      - mynet
  ldap:
    image: adriaquintero61/ldapserver19:practica
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports:
      - "389:389"
    networks:
      - mynet
networks:
  mynet:
